{-# OPTIONS --safe --without-K #-}
-- SPDX-License-Identifier: MPL-2.0
-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell
--
-- The certified finite checker agrees with the explorer, row for row.
--
-- `ExplorerTable.expected` is generated by `generate-table.js` from the model
-- that `explorer-model.js` loads out of the unchanged
-- `residual-evidence-explorer.html`. `Checker.table` is computed by the
-- verified checker over all 546 configurations. `refl` closes the goal only
-- when the two lists are identical after normalisation, so any drift in the
-- explorer, the generator or the checker is a type error here.
module Correspondence where

open import Agda.Builtin.Equality using (_≡_; refl)
open import ResidualEvidence.Finite.Checker using (table)
open import ExplorerTable using (expected)

checker-matches-explorer : table ≡ expected
checker-matches-explorer = refl
