// SPDX-License-Identifier: MPL-2.0
// SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell
'use strict';

// Emits tests/correspondence/ExplorerTable.agda from the explorer's own model.
//
//   bun tests/correspondence/generate-table.js [--out <path>] [--view <v>] [--module <Name>]
//
// Default: every configuration (546 rows), module ExplorerTable, written to
// tests/correspondence/ExplorerTable.agda. `--view` restricts to one view
// (182 rows; the module then defaults to ExplorerTable<View>, e.g.
// ExplorerTableExact, and the output path to <Module>.agda next to this
// file). Output is deterministic, LF-terminated, with one trailing newline.
//
// Only the CLI writes anything. Importing this module is side-effect free so
// the drift test in explorer.test.js compares against the COMMITTED file,
// never against a file it just rewrote.

import { writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { VIEWS, configs, makeCase, rowOf } from './explorer-model.js';

const MODEL_NAME = makeCase({ residual: 0, noiseBound: 0, view: 'exact', assumeZero: false }).model;
if (MODEL_NAME !== 'signed-integer-v1') {
  throw new Error(`unexpected model name ${JSON.stringify(MODEL_NAME)}; the emitted header names 'signed-integer-v1'`);
}

const VIEW = Object.freeze({ exact: 'exact', sign: 'sign', magnitude: 'magnitude' });
const PRESENCE = Object.freeze({
  entailed: 'entailed',
  refuted: 'refuted',
  unresolved: 'unresolved',
  inconsistent: 'inconsistent',
});
const IDENTITY = Object.freeze({
  identified: 'identified',
  unidentified: 'unidentified',
  inconsistent: 'no-candidate',
});

function spell(table, key, what) {
  if (!Object.hasOwn(table, key)) throw new Error(`cannot spell ${what} ${JSON.stringify(key)} in Agda`);
  return table[key];
}

// Agda.Builtin.Int: pos n for n ≥ 0, negsuc n for −(n+1). Never a negative literal.
export function int(n) {
  if (!Number.isInteger(n)) throw new Error(`not an integer: ${n}`);
  return n >= 0 ? `pos ${n}` : `negsuc ${-n - 1}`;
}

export function nat(n) {
  if (!Number.isInteger(n) || n < 0) throw new Error(`not a natural number: ${n}`);
  return String(n);
}

export function intList(values) {
  return values.length === 0 ? '[]' : `(${values.map(int).join(' ∷ ')} ∷ [])`;
}

export function rowLine(r) {
  return [
    'row',
    `(${int(r.residual)})`,
    nat(r.noiseBound),
    spell(VIEW, r.view, 'view'),
    r.assumeZero ? 'true' : 'false',
    nat(r.count),
    spell(PRESENCE, r.presence, 'presence'),
    spell(IDENTITY, r.identity, 'identity'),
    intList(r.values),
  ].join(' ');
}

export function renderTable({ view = null, module = 'ExplorerTable' } = {}) {
  if (view !== null && !VIEWS.includes(view)) {
    throw new Error(`unknown view ${JSON.stringify(view)}; expected one of ${VIEWS.join(', ')}`);
  }
  if (!/^[A-Z][A-Za-z0-9]*$/.test(module)) {
    throw new Error(`module name must be a simple capitalised identifier, got ${JSON.stringify(module)}`);
  }
  const lines = [
    '{-# OPTIONS --safe --without-K #-}',
    '-- SPDX-License-Identifier: MPL-2.0',
    '-- SPDX-FileCopyrightText: 2026 Jonathan D.A. Jewell',
    '-- GENERATED by tests/correspondence/generate-table.js from residual-evidence-explorer.html',
    `-- (model '${MODEL_NAME}'). Do not edit; regenerate and diff.`,
    '',
    `module ${module} where`,
    '',
    'open import Agda.Builtin.Int using (Int; pos; negsuc)',
    'open import Agda.Builtin.Bool using (Bool; true; false)',
    'open import Agda.Builtin.List using (List; []; _∷_)',
    'open import ResidualEvidence.Finite.Row',
    '',
    'expected : List Row',
    'expected =',
  ];
  let first = true;
  for (const cfg of configs()) {
    if (view !== null && cfg.view !== view) continue;
    lines.push(`${first ? '    ' : '  ∷ '}${rowLine(rowOf(cfg))}`);
    first = false;
  }
  lines.push('  ∷ []');
  return lines.join('\n') + '\n';
}

function capitalise(s) {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

function parseArgs(argv) {
  const opts = { out: null, view: null, module: null };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    const value = () => {
      if (i + 1 >= argv.length) throw new Error(`${a} needs a value`);
      return argv[++i];
    };
    if (a === '--out') opts.out = value();
    else if (a === '--view') opts.view = value();
    else if (a === '--module') opts.module = value();
    else throw new Error(`unknown argument ${JSON.stringify(a)}`);
  }
  if (opts.view !== null && !VIEWS.includes(opts.view)) {
    throw new Error(`--view must be one of ${VIEWS.join(', ')}, got ${JSON.stringify(opts.view)}`);
  }
  if (opts.module === null) opts.module = opts.view === null ? 'ExplorerTable' : `ExplorerTable${capitalise(opts.view)}`;
  if (opts.out === null) opts.out = resolve(import.meta.dir, `${opts.module}.agda`);
  return opts;
}

if (import.meta.main) {
  const opts = parseArgs(process.argv.slice(2));
  const text = renderTable({ view: opts.view, module: opts.module });
  writeFileSync(opts.out, text, 'utf8');
  const rows = text.split('\n').filter(l => /^(    |  ∷ )row /.test(l)).length;
  console.log(`wrote ${opts.out} (${rows} rows, module ${opts.module})`);
}
